### ISSUE TITLE
syncthing crashes when adding new folders

### ISSUE THREAD

**Issue by Eddy2909** [Zillode/syncthing-silk#18] opened 2015-08-13 08:33 UTC

**Comment by Zillode** [comment] 2015-08-13 09:51
Can you grab me a logcat? I cannot reproduce this

**Comment by Eddy2909** [comment] 2015-08-13 09:59
D/SyncthingInstance(17100): onStartCommand Intent { act=syncthing.android.action.fgstatechanged cmp=syncthing.android/.service.SyncthingInstance (has extras) }
I/Timeline( 652): Timeline: Activity_windows_visible id: ActivityRecord{41aa80a0 u0 syncthing.android/.ui.LauncherActivity t50} time:24004594
V/MortarDialogFragment(17073): ->onCreate syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
D/EditFragment(17073): Created new fragment scope syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
V/MortarDialogFragment(17073): <-onCreate syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
V/MortarDialogFragment(17073): ->onActivityCreated syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
V/MortarDialogFragment(17073): <-onActivityCreated syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
V/MortarDialogFragment(17073): ->onDestroy syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
D/MortarDialogFragment(17073): Destroying fragment scope syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
V/MortarDialogFragment(17073): <-onDestroy syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
I/SyncthingThread$LogWriterThread(17100): [YUDLD] 09:57:45 INFO: Established secure connection to 7QCULIP-XXXXXXXX-GJC57AF at 192.168.0.106:36321-XXXXXXX:22000
I/SyncthingThread$LogWriterThread(17100): [YUDLD] 09:57:45 INFO: Device 7QCULIP-XXXXXXXXX-GJC57AF client is "syncthing v0.11.19"
I/SyncthingThread$LogWriterThread(17100): [YUDLD] 09:57:45 INFO: Device 7QCULIP-XXXXXXXXXXXXXXX-GJC57AF name is "BigCloud"
V/MortarFragment(17073): ->onCreate syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
D/MortarFragment(17073): Reusing fragment scope syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarFragment(17073): <-onCreate syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarFragment(17073): ->onActivityCreated syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarFragment(17073): <-onActivityCreated syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarFragment(17073): ->onDestroy syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
D/MortarFragment(17073): Destroying fragment scope syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarFragment(17073): <-onDestroy syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY
V/MortarDialogFragment(17073): ->onCreate syncthing.android.ui.session.edit.EditFolderScreen@@@INVALID@@@
E/AndroidRuntime(17073): Process: syncthing.android, PID: 17073
E/AndroidRuntime(17073): java.lang.IllegalStateException: Scope syncthing.android.ui.session.SessionScreentzX10mgaL6Zj-fsy4AQgOQLdp95tU4nY was destroyed
E/AndroidRuntime(17073): at syncthing.android.ui.session.edit.EditFragment.findOrMakeScope(EditFragment.java:160)
E/AndroidRuntime(17073): at syncthing.android.ui.session.edit.EditFragment.onCreate(EditFragment.java:177)
W/ActivityManager( 652): Force finishing activity syncthing.android/.ui.LauncherActivity
W/ActivityManager( 652): Activity pause timeout for ActivityRecord{41aa80a0 u0 syncthing.android/.ui.LauncherActivity t50 f}
I/ActivityManager( 652): Process syncthing.android (pid 17073) has died.
I/WindowState( 652): WIN DEATH: Window{42395cd8 u0 syncthing.android/syncthing.android.ui.LauncherActivity}

**Comment by Eddy2909** [comment] 2015-08-13 10:01
got some screenshots posted for #19

**Comment by Eddy2909** [comment] 2015-08-13 10:20
if clicking on "new folder" out of homescreen, it works.
what I did:
open left panel, click device, click "add folder"

**Comment by Zillode** [comment] 2015-08-13 17:51
Can you add some screenshots? Both the menu and the dropdown button work for me

**Comment by Eddy2909** [comment] 2015-08-13 18:06
![screenshot_2015-08-13-20-03-10](https://cloud.githubusercontent.com/assets/12877411/9257606/ba5b19c0-41f6-11e5-88e1-28089d708156.png)
![screenshot_2015-08-13-20-03-15](https://cloud.githubusercontent.com/assets/12877411/9257607/ba7b5442-41f6-11e5-8c95-0e3a24a51c77.png)
![screenshot_2015-08-13-20-03-20](https://cloud.githubusercontent.com/assets/12877411/9257608/ba8a11da-41f6-11e5-9f4e-bb979bc299de.png)
![screenshot_2015-08-13-20-03-03](https://cloud.githubusercontent.com/assets/12877411/9257609/ba90d556-41f6-11e5-93e5-a304876a6e36.png)

**Comment by Zillode** [comment] 2015-08-13 18:14
What android version and device is this?

**Comment by Eddy2909** [comment] 2015-08-13 18:24
![screenshot_2015-08-13-20-24-23](https://cloud.githubusercontent.com/assets/12877411/9258019/560b0c8e-41f9-11e5-821a-a2455c8ed6a7.png)

**Comment by Zillode** [comment] 2015-08-13 22:02
Does it also crash when adding a folder to the local instance (bigcloud?)

**Comment by Eddy2909** [comment] 2015-08-13 22:06
matadors4 is the local instance.. it only crashes when adding a folder to the local device.. :-(

**Comment by Zillode** [comment] 2015-11-12 23:39
Fixed in upstream

**Closed by Zillode** 2015-11-12 23:39 UTC
